List<String> words = [
  "Ephemeral",
  "Serendipity",
  "Ethereal",
  "Mellifluous",
  "Ineffable",
  "Sonorous",
  "Halcyon",
  "Sonder",
  "Luminous",
  "Petrichor",
  "Oblivion",
  "Zephyr",
  "Euphoria",
  "Resonance",
  "Aurora",
  "Nebula",
  "Solitude",
  "Labyrinth",
  "Obsidian",
  "Vellichor",
  "Zenith",
  "Nostalgia",
  "Epiphany",
  "Eloquent",
  "Mirage",
  "Cascade",
  "Renaissance",
  "Obscura",
  "Luminescence",
  "Harmony",
];

List<String> definitions = [
  "Lasting for a very short time.",
  "Finding something good without looking for it.",
  "Extremely delicate or light; seeming too perfect for this world.",
  "Sweet-sounding or pleasant to hear.",
  "Too great or extreme to be expressed in words.",
  "Deep, rich, and full in sound.",
  "Calm, peaceful, and happy.",
  "The realization that every passerby has a life as vivid and complex as your own.",
  "Giving off light; glowing brightly.",
  "The earthy smell after rain.",
  "The state of being unaware or forgotten.",
  "A soft, gentle breeze.",
  "A feeling of intense happiness.",
  "A deep or meaningful quality that stays with you.",
  "A natural light display in the sky, like the Northern Lights.",
  "A huge cloud of gas and dust in space.",
  "The state of being alone, often peacefully.",
  "A complex maze of paths or passages.",
  "A dark volcanic glass-like rock.",
  "The strange wistfulness of old bookshops.",
  "The highest point or peak.",
  "A sentimental longing for the past.",
  "A sudden realisation or insight.",
  "Fluent or persuasive in speaking or writing.",
  "An optical illusion, often seen in deserts or on hot roads.",
  "A small waterfall or something falling in stages.",
  "A revival or rebirth, especially of art and culture.",
  "Something hidden, dark, or mysterious.",
  "Light produced without heat.",
  "A pleasing combination of sounds or ideas.",
];
